package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/rizzimatheus/password-graphql-service/graph/model"
)

// Verify is the resolver for the Verify field.
func (r *queryResolver) Verify(ctx context.Context, password string, rules []*model.Rule) (*model.Response, error) {
	noMatch, err := model.VarifyRules(password, rules)
	if err != nil {
		return nil, err
	}

	verify := len(noMatch) == 0

	payload := model.Response{
		Verify:  verify,
		NoMatch: noMatch,
	}

	return &payload, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
